#define MAX_FRACTIONS 24

enum _:frac_ids {
    fNONE = 0,
	fLSPD = 1,
	fSFPD = 2,
	fLVPD = 3,
	fFBI = 4,
	fMAYOR = 5,
	fARMYSF = 6,
	fARMYLV = 7,
	fMEDICLS = 8,
	fMEDICSF = 9,
	fMEDICLV = 10,
	fLSNEWS = 11,
	fSFNEWS = 12,
	fLVNEWS = 13,
	fINSTRUCTORS = 14,
	fLCN = 15,
	fYAKUZA = 16,
	fRM = 17,
	fBALLAS = 18,
	fVAGOS = 19,
	fGROVE = 20,
	fAZTEC = 21,
	fRIFA = 22,
	fWHITEHOUSE = 23
};